version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vallencia
    ports:
      - "0.0.0.0:9000:80" 
    volumes:
      - .:/var/www/html/Valencia-Lighting
    env_file:
      - .env
    networks:
      - valencia-network

networks:
  valencia-network:
    driver: bridge
